"""Init

Revision ID: 795121aeb030
Revises: 37ff601ceca7
Create Date: 2023-06-25 10:14:44.376673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795121aeb030'
down_revision = '37ff601ceca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
